version: "3.1"
services:
  db-dev:
    container_name: db-dev
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DEV_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DEV_DATABASE}
      - MYSQL_USER=${MYSQL_DEV_USER}
      - MYSQL_PASSWORD=${MYSQL_DEV_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - dbdev:/var/lib/mysql
    env_file:
      - .env
  api-dev:
    container_name: api-dev
    restart: always
    depends_on:
      - db-dev
    image: test
    ports:
      - 8081:4000
    environment:
      - DB_HOST=${DB_DEV_HOST}
      - DB_USER=${DB_DEV_USER}
      - DB_PASSWORD=${DB_DEV_PASSWORD}
      - DB_NAME=${DB_DEV_NAME}
      - DB_PORT=${DB_DEV_PORT}
    env_file:
      - .env
  db-test:
    container_name: db-test
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_TEST_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_TEST_DATABASE}
      - MYSQL_USER=${MYSQL_TEST_USER}
      - MYSQL_PASSWORD=${MYSQL_TEST_PASSWORD}
    env_file:
      - .env
    ports:
      - 3307:3306
    volumes:
      - dbtest:/var/lib/mysql
  api-test:
    container_name: api-test
    restart: always
    depends_on:
      - db-test
    image: test
    ports:
      - 8082:4000
    environment:
      - DB_HOST=${DB_TEST_HOST}
      - DB_USER=${DB_TEST_USER}
      - DB_PASSWORD=${DB_TEST_PASSWORD}
      - DB_NAME=${DB_TEST_NAME}
      - DB_PORT=${DB_TEST_PORT}
    env_file:
      - .env
volumes:
  dbdev:
  dbtest:
